spring:
  application:
    name: zuul-server
  profiles:
    active: local

server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/