spring:
  application:
    name: opiniones-ms
  profiles:
    active: local

server:
  port: 0

---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/